Repository cd-carpe-diem/Carpe-Diem-BE, pull requests merged in 2023-02, with the labels that each got.

#1 Feat: S3 비디오 업로드
  test/uploadVideo.js
Labels: ✅ Test, ✨ Feat

#2 Refactor: 서버 3 레이어 계층 구조화
  .gitignore
  app.js
  bin/www
  package-lock.json
  package.json
  public/stylesheets/style.css
  routes/index.js
  routes/index.ts
  routes/users.ts
  src/app.ts
  src/config/index.ts
  src/loaders/express.ts
  src/loaders/index.ts
  src/loaders/logger.ts
  test/uploadVideo.ts
  tsconfig.json
  views/error.jade
  views/index.jade
  views/layout.jade
Labels: ♻️ Refactor

#3 Feat: 비디오 S3에 저장
  .gitignore
  app.js
  bin/www
  package-lock.json
  package.json
  public/stylesheets/style.css
  routes/index.js
  routes/users.js
  src/api/camera.ts
  src/app.ts
  src/config/index.ts
  src/constant/responseMessage.ts
  src/constant/statusCode.ts
  src/loaders/express.ts
  src/loaders/index.ts
  src/loaders/logger.ts
  src/services/camera.ts
  test/uploadVideo.js
  tsconfig.json
  views/error.jade
  views/index.jade
  views/layout.jade
Labels: ✨ Feat

#4 Merge from Feat/CD-19 to develop
  .gitignore
  app.js
  bin/www
  package-lock.json
  package.json
  public/stylesheets/style.css
  routes/index.js
  routes/users.js
  src/api/camera.ts
  src/app.ts
  src/config/index.ts
  src/constant/responseMessage.ts
  src/constant/statusCode.ts
  src/loaders/express.ts
  src/loaders/index.ts
  src/loaders/logger.ts
  src/services/camera.ts
  tsconfig.json
  views/error.jade
  views/index.jade
  views/layout.jade
Labels: 😀 Develop Merge

#5 Feat: S3 동영상 객체 목록 가져오기
  src/config/index.ts
  src/services/camera.ts
  src/services/getObjectUrlS3Bucket.ts
Labels: ✅ Test, ✨ Feat

#6 Feat: 실시간 카메라 영상 S3 저장
  package.json
  src/api/camera.ts
  src/app.ts
  src/config/index.ts
  src/constant/statusCode.ts
  src/loaders/express.ts
  src/loaders/index.ts
  src/loaders/multer.ts
  src/models/Expression.ts
  src/models/index.ts
  src/services/camera.ts
Labels: ✨ Feat

#8 Feat: 카드 리스트 GET API
  src/api/card.ts
  src/app.ts
  src/common/constant/responseMessage.ts
  src/services/card.ts
Labels: ✨ Feat

#9 Fix: get cards API request 변경
  src/api/card.ts
  src/services/card.ts
Labels: 🐛 Fix

#10 Feat: 단일 페이지 상세정보 GET API
  src/api/card.ts
  src/services/card.ts
Labels: ✨ Feat

#11 Feat/cd 84
  src/api/card.ts
  src/services/card.ts
Labels: 😀 Merge Develop

#12 Feat: API Swagger 적용
  package.json
  src/app.ts
  src/docs/api/card/card.ts
  src/docs/api/card/index.ts
  src/docs/index.ts
  src/loaders/express.ts
  src/loaders/index.ts
  src/loaders/swagger.ts
Labels: ✨ Feat

#13 Feat: 단일 페이지 삭제 DELETE API
  src/api/card.ts
  src/services/card.ts
Labels: ✨ Feat, 😀 Merge Develop

#14 Feat: 단일 페이지 타이틀 수정 PUT API
  src/api/card.ts
  src/common/constant/responseMessage.ts
  src/services/card.ts
Labels: ✨ Feat, 😀 Merge Develop

#15 Fix: 단일 페이지 타이틀 수정 PUT API
  src/api/card.ts
  src/app.ts
  src/docs/api/card/card.ts
  src/services/card.ts
Labels: 🐛 Fix, 😀 Merge Develop

#16 Feat: 각 영상 FFMPEG를 통해 ".webm" 확장자 ".mp4" 로 변경 및 특정 시간에 ".jpg" 파일 추출
  src/lambda/makeThumbnail.py
Labels: ✨ Feat

#18 Merge from Feat/CD-80 to develop #16
  src/lambda/makeThumbnail.py
Labels: 😀 Merge Develop

#19 Fix: 단일 페이지 삭제 DELETE API
  src/api/card.ts
  src/app.ts
  src/loaders/express.ts
Labels: 🐛 Fix, 😀 Merge Develop

#20 Feat: 사용자 이미지 GET API 추가
  src/api/camera.ts
  src/common/constant/responseMessage.ts
  src/loaders/multer.ts
  src/models/Expression.ts
  src/models/Usim.ts
  src/services/camera.ts
Labels: ✨ Feat

#21 Feat: 앨범 리스트 GET API
  src/api/album.ts
  src/api/card.ts
  src/app.ts
  src/common/constant/responseMessage.ts
  src/services/album.ts
  src/services/card.ts
Labels: ✨ Feat

#22 Feat: 앨범 로드 GET API
  src/api/album.ts
  src/services/album.ts
Labels: ✨ Feat

#23 Feat: 앨범 삭제 DELETE API
  src/api/album.ts
  src/services/album.ts
Labels: ✨ Feat

#26 Merge from Feat/CD-29 to develop #25
  src/api/album.ts
  src/services/album.ts
Labels: 😀 Merge Develop

#27 앨범 로드 GET API Swagger 적용
  src/docs/api/album/album.ts
  src/docs/api/album/index.ts
  src/docs/api/card/card.ts
  src/docs/index.ts
Labels: ✨ Feat

#30 Merge from Feat/CD-29 to develop #27
  src/docs/api/album/album.ts
  src/docs/api/album/index.ts
  src/docs/api/card/card.ts
  src/docs/index.ts
Labels: 😀 Merge Develop

#28 앨범 삭제 DELETE API Swagger 적용
  src/docs/api/album/album.ts
  src/docs/api/album/index.ts
  src/docs/api/card/card.ts
  src/docs/index.ts
Labels: ✨ Feat

#31 Merge from Feat/CD-92 to develop #28
  src/docs/api/album/album.ts
Labels: 😀 Merge Develop

#29 Feat: 앨범 타이틀 수정 PUT API
  src/api/album.ts
  src/services/album.ts
Labels: ✨ Feat, 😀 Merge Develop

#33 Feat: 앨범 타이틀 수정 PUT API Swagger 적용, 코드정리
  src/api/card.ts
  src/docs/api/album/album.ts
  src/docs/api/card/card.ts
Labels: ✨ Feat, 😀 Merge Develop

#34 Feat: 최근 저장한 영상 정보 로드
  src/api/camera.ts
  src/common/constant/responseMessage.ts
  src/loaders/swagger.ts
  src/models/Expression.ts
  src/models/index.ts
  src/services/camera.ts
Labels: 🐛 Fix, ✨ Feat

#37 Merge from Feat/CD-88 to develop #36
  src/lambda/pickBestCutEveryweek.py
Labels: 😀 Merge Develop

#38 Change: 단일 앨범 로드 API 수정
  src/api/album.ts
  src/docs/api/album/album.ts
  src/services/album.ts
  src/services/camera.ts
Labels: ✨ Feat

#39 Feat: 사용자 앨범 생성 API 완료
  package.json
  src/api/album.ts
  src/common/constant/responseMessage.ts
  src/docs/api/album/album.ts
  src/models/Album.ts
  src/services/album.ts
Labels: ✨ Feat

#40 Feat: 소셜 로그인 구현
  package.json
  src/api/auth.js
  src/api/login.ts
  src/app.ts
  src/passport/google.ts
  src/passport/index.ts
Labels: ✨ Feat

#42 [CI/CD] GithubActions & Docker 적용
  .dockerignore
  Dockerfile
  package.json
Labels: ✨ Feat, 😀 Merge Develop

#41 Feat: passport google login server 도입
  package.json
  src/api/auth.ts
  src/api/camera.ts
  src/app.ts
  src/common/constant/responseMessage.ts
  src/config/index.ts
  src/config/passport/googleAuth.ts
  src/config/passport/index.ts
  src/docs/api/auth/auth.ts
  src/docs/api/auth/index.ts
  src/docs/api/camera/camera.ts
  src/docs/api/camera/index.ts
  src/docs/index.ts
  src/loaders/index.ts
  src/loaders/multer.ts
  src/loaders/swagger.ts
  src/models/User.ts
  src/models/index.ts
  src/services/auth.ts
  src/types/expressRequest.ts
  src/types/passport.d.ts
Labels: 🐛 Fix, ✨ Feat

#44 [RUD] Card API 로그인 이후 서비스 이용 가능하도록 수정
  src/api/card.ts
  src/docs/api/card/card.ts
Labels: 🐛 Fix, ♻️ Refactor

#45 Merge from Feat/CD-116 to develop #44
  src/api/card.ts
  src/docs/api/card/card.ts
Labels: 😀 Merge Develop

#46 Feat: 친구 목록 조회 GET API
  src/api/friend.ts
  src/app.ts
  src/common/constant/responseMessage.ts
  src/config/passport/googleAuth.ts
  src/models/Friend.ts
  src/models/User.ts
  src/models/index.ts
  src/services/auth.ts
  src/services/friend.ts
Labels: ✨ Feat, 😀 Merge Develop

#48 Merge from Feat/CD-122 to develop #47
  src/api/user.ts
  src/docs/api/user/user.ts
Labels: 😀 Merge Develop

#49 Feat: 친구 검색 GET API
  src/api/user.ts
  src/common/constant/responseMessage.ts
  src/services/user.ts
Labels: ✨ Feat, 😀 Merge Develop

#50 Feat: 친구 삭제 DELETE API
  src/api/card.ts
  src/api/friend.ts
  src/services/friend.ts
Labels: ✨ Feat, 😀 Merge Develop

#52 Feat: 모든 유저 불러오기 GET API
  src/api/friend.ts
  src/api/user.ts
  src/common/constant/responseMessage.ts
  src/services/user.ts
Labels: ✨ Feat, 😀 Merge Develop

#53 Feat: 친구 요청 보내기 CREATE API
  src/api/friend.ts
  src/common/constant/responseMessage.ts
  src/services/friend.ts
Labels: ✨ Feat, 😀 Merge Develop

#56 [CRUD] Backend 앨범 API 로그인 이후 서비스 이용 가능하도록 수정
  src/api/album.ts
  src/docs/api/album/album.ts
Labels: ♻️ Refactor, 📝 Docs

#57 Merge from Change/CD-129 to develop #56
  src/api/album.ts
  src/docs/api/album/album.ts
Labels: 😀 Merge Develop

#58 Feat: 받은 친구 요청 목록 API
  src/api/friend.ts
  src/common/constant/responseMessage.ts
  src/services/friend.ts
Labels: 🐛 Fix, ✨ Feat, 😀 Merge Develop

#59 Feat: 배포 설정 추가
  Dockerfile
  package.json
  src/app.ts
  src/config/index.ts
  src/loaders/logger/devLogger.ts
  src/loaders/logger/index.ts
  src/loaders/logger/productionLogger.ts
  src/loaders/multer.ts
Labels: ♻️ Refactor, ✨ Feat

#61 Feat: 친구 API들 swagger 작업
  src/api/user.ts
  src/config/passport/index.ts
  src/docs/api/album/album.ts
  src/docs/api/friend/friend.ts
  src/docs/api/friend/index.ts
  src/docs/api/user/user.ts
  src/docs/index.ts
  src/services/album.ts
  src/services/auth.ts
  src/services/camera.ts
  src/services/card.ts
  src/services/friend.ts
  src/services/user.ts
Labels: 🐛 Fix, ✨ Feat, 😀 Merge Develop

#62 Feat: 친구 앨범 확인 GET API
  src/api/album.ts
  src/api/friend.ts
  src/common/constant/responseMessage.ts
  src/models/Album.ts
  src/services/album.ts
  src/services/friend.ts
Labels: ✨ Feat, 😀 Merge Develop

#63 Feat: 원격 카메라 socket 연결
  Dockerfile
  src/app.ts
Labels: ✨ Feat

#64 Feat: 유저 이미지 S3 저장
  src/api/camera.ts
  src/api/usim.ts
  src/app.ts
  src/loaders/multer.ts
  src/services/usim.ts
Labels: ✨ Feat

#65 Feat: 로그인 이탈 페이지 구현 및 usim 수정
  src/api/camera.ts
  src/api/index.ts
  src/api/usim.ts
  src/app.ts
  src/loaders/multer.ts
  src/services/camera.ts
  src/services/usim.ts
Labels: ✨ Feat

#66 Feat: 친구 서재 보기 API
  src/api/friend.ts
  src/api/friendAlbum.ts
  src/app.ts
  src/services/album.ts
  src/services/friendAlbum.ts
Labels: ✨ Feat, 😀 Merge Develop

#67 Feat: 페이지네이션 - 카드 API
  .github/workflows/main.yml
  Dockerfile
  package.json
  src/api/album.ts
  src/api/camera.ts
  src/api/card.ts
  src/api/friend.ts
  src/api/friendAlbum.ts
  src/api/index.ts
  src/api/user.ts
  src/app.ts
  src/common/constant/responseMessage.ts
  src/config/index.ts
  src/config/passport/index.ts
  src/docs/api/album/album.ts
  src/docs/api/friend/friend.ts
  src/docs/api/friend/index.ts
  src/docs/api/user/user.ts
  src/docs/index.ts
  src/loaders/logger/devLogger.ts
  src/loaders/logger/index.ts
  src/loaders/logger/productionLogger.ts
  src/loaders/multer.ts
  src/models/Album.ts
  src/services/album.ts
  src/services/auth.ts
  src/services/camera.ts
  src/services/card.ts
  src/services/friend.ts
  src/services/friendAlbum.ts
  src/services/user.ts
Labels: ✨ Feat

#69 Feat: 페이지네이션-카드(무한 스크롤 추가)
  src/api/album.ts
  src/api/card.ts
  src/app.ts
  src/services/album.ts
  src/services/card.ts
Labels: 😀 Merge Develop

#68 Feat: 페이지네이션-앨범(무한 스크롤 추가) API
  src/api/album.ts
  src/api/card.ts
  src/app.ts
  src/services/album.ts
  src/services/card.ts
Labels: ✨ Feat
